cmake_minimum_required(VERSION 3.22.1)
project(nfbbridge LANGUAGES CXX)
add_library(nfbcore SHARED IMPORTED)
set_target_properties(nfbcore PROPERTIES IMPORTED_LOCATION "${NFB_CORE_DIR}/${ANDROID_ABI}/libnfbcore.so")
add_library(nfbbridge SHARED bridge.cpp)
target_compile_features(nfbbridge PRIVATE cxx_std_17)
target_include_directories(nfbbridge PRIVATE "${NFB_CORE_DIR}/${ANDROID_ABI}")
target_link_libraries(nfbbridge PRIVATE nfbcore)
target_link_options(nfbbridge PRIVATE "-Wl,-z,max-page-size=16384")
